'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Node
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Keys", [Namespace]:="http://schemas.datacontract.org/2004/07/DC.Common.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Keys
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EncryptedWIFPrivateKeyField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField() As Byte
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrivateKeyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PublicKeyField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EncryptedWIFPrivateKey() As Byte()
            Get
                Return Me.EncryptedWIFPrivateKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EncryptedWIFPrivateKeyField, value) <> true) Then
                    Me.EncryptedWIFPrivateKeyField = value
                    Me.RaisePropertyChanged("EncryptedWIFPrivateKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As Byte()
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PrivateKey() As String
            Get
                Return Me.PrivateKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrivateKeyField, value) <> true) Then
                    Me.PrivateKeyField = value
                    Me.RaisePropertyChanged("PrivateKey")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PublicKey() As String
            Get
                Return Me.PublicKeyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PublicKeyField, value) <> true) Then
                    Me.PublicKeyField = value
                    Me.RaisePropertyChanged("PublicKey")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Order", [Namespace]:="http://schemas.datacontract.org/2004/07/DC.Common.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Order
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private Addressk__BackingFieldField As String
        
        Private BTCk__BackingFieldField As Decimal
        
        Private Idk__BackingFieldField As System.Guid
        
        Private PrivateKeyAsBase64k__BackingFieldField As String
        
        Private PrivateKeyAsByteArrayk__BackingFieldField() As Byte
        
        Private PrivateKeyk__BackingFieldField As String
        
        Private Txnk__BackingFieldField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<Address>k__BackingField", IsRequired:=true)>  _
        Public Property Addressk__BackingField() As String
            Get
                Return Me.Addressk__BackingFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Addressk__BackingFieldField, value) <> true) Then
                    Me.Addressk__BackingFieldField = value
                    Me.RaisePropertyChanged("Addressk__BackingField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<BTC>k__BackingField", IsRequired:=true)>  _
        Public Property BTCk__BackingField() As Decimal
            Get
                Return Me.BTCk__BackingFieldField
            End Get
            Set
                If (Me.BTCk__BackingFieldField.Equals(value) <> true) Then
                    Me.BTCk__BackingFieldField = value
                    Me.RaisePropertyChanged("BTCk__BackingField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<Id>k__BackingField", IsRequired:=true)>  _
        Public Property Idk__BackingField() As System.Guid
            Get
                Return Me.Idk__BackingFieldField
            End Get
            Set
                If (Me.Idk__BackingFieldField.Equals(value) <> true) Then
                    Me.Idk__BackingFieldField = value
                    Me.RaisePropertyChanged("Idk__BackingField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<PrivateKeyAsBase64>k__BackingField", IsRequired:=true)>  _
        Public Property PrivateKeyAsBase64k__BackingField() As String
            Get
                Return Me.PrivateKeyAsBase64k__BackingFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrivateKeyAsBase64k__BackingFieldField, value) <> true) Then
                    Me.PrivateKeyAsBase64k__BackingFieldField = value
                    Me.RaisePropertyChanged("PrivateKeyAsBase64k__BackingField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<PrivateKeyAsByteArray>k__BackingField", IsRequired:=true)>  _
        Public Property PrivateKeyAsByteArrayk__BackingField() As Byte()
            Get
                Return Me.PrivateKeyAsByteArrayk__BackingFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrivateKeyAsByteArrayk__BackingFieldField, value) <> true) Then
                    Me.PrivateKeyAsByteArrayk__BackingFieldField = value
                    Me.RaisePropertyChanged("PrivateKeyAsByteArrayk__BackingField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<PrivateKey>k__BackingField", IsRequired:=true)>  _
        Public Property PrivateKeyk__BackingField() As String
            Get
                Return Me.PrivateKeyk__BackingFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PrivateKeyk__BackingFieldField, value) <> true) Then
                    Me.PrivateKeyk__BackingFieldField = value
                    Me.RaisePropertyChanged("PrivateKeyk__BackingField")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Name:="<Txn>k__BackingField", IsRequired:=true)>  _
        Public Property Txnk__BackingField() As String
            Get
                Return Me.Txnk__BackingFieldField
            End Get
            Set
                If (Object.ReferenceEquals(Me.Txnk__BackingFieldField, value) <> true) Then
                    Me.Txnk__BackingFieldField = value
                    Me.RaisePropertyChanged("Txnk__BackingField")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schema.diamondcircle.net/v1", ConfigurationName:="Node.IAtm")>  _
    Public Interface IAtm
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/CreatePublicEncryptedPrivateKey", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/CreatePublicEncryptedPrivateKeyResponse")>  _
        Function CreatePublicEncryptedPrivateKey() As Node.Keys
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/CreatePublicEncryptedPrivateKey", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/CreatePublicEncryptedPrivateKeyResponse")>  _
        Function CreatePublicEncryptedPrivateKeyAsync() As System.Threading.Tasks.Task(Of Node.Keys)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/CreateOrder", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/CreateOrderResponse")>  _
        Function CreateOrder(ByVal publicKey As String, ByVal amount As Decimal) As Node.Order
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/CreateOrder", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/CreateOrderResponse")>  _
        Function CreateOrderAsync(ByVal publicKey As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of Node.Order)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/TransferCoinsToBuyer", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/TransferCoinsToBuyerResponse")>  _
        Function TransferCoinsToBuyer(ByVal cardId As String, ByVal amount As Decimal) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/TransferCoinsToBuyer", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/TransferCoinsToBuyerResponse")>  _
        Function TransferCoinsToBuyerAsync(ByVal cardId As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/ReceiveCoins", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/ReceiveCoinsResponse")>  _
        Function ReceiveCoins(ByVal encryptedPrivateKey As String, ByVal cardId As String, ByVal destinationAddress As String, ByVal amount As Decimal) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/ReceiveCoins", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/ReceiveCoinsResponse")>  _
        Function ReceiveCoinsAsync(ByVal encryptedPrivateKey As String, ByVal cardId As String, ByVal destinationAddress As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/GetBalance", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/GetBalanceResponse")>  _
        Function GetBalance(ByVal address As String, ByVal confirmations As Short) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/GetBalance", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/GetBalanceResponse")>  _
        Function GetBalanceAsync(ByVal address As String, ByVal confirmations As Short) As System.Threading.Tasks.Task(Of Decimal)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/SendBitcoins", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/SendBitcoinsResponse")>  _
        Function SendBitcoins(ByVal encryptedPrivateKey As String, ByVal password As String, ByVal destinationAddress As String, ByVal amount As Decimal) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/SendBitcoins", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/SendBitcoinsResponse")>  _
        Function SendBitcoinsAsync(ByVal encryptedPrivateKey As String, ByVal password As String, ByVal destinationAddress As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/SendEmail", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/SendEmailResponse")>  _
        Sub SendEmail(ByVal toAddress As String, ByVal subject As String, ByVal body As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schema.diamondcircle.net/v1/IAtm/SendEmail", ReplyAction:="http://schema.diamondcircle.net/v1/IAtm/SendEmailResponse")>  _
        Function SendEmailAsync(ByVal toAddress As String, ByVal subject As String, ByVal body As String) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAtmChannel
        Inherits Node.IAtm, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AtmClient
        Inherits System.ServiceModel.ClientBase(Of Node.IAtm)
        Implements Node.IAtm
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreatePublicEncryptedPrivateKey() As Node.Keys Implements Node.IAtm.CreatePublicEncryptedPrivateKey
            Return MyBase.Channel.CreatePublicEncryptedPrivateKey
        End Function
        
        Public Function CreatePublicEncryptedPrivateKeyAsync() As System.Threading.Tasks.Task(Of Node.Keys) Implements Node.IAtm.CreatePublicEncryptedPrivateKeyAsync
            Return MyBase.Channel.CreatePublicEncryptedPrivateKeyAsync
        End Function
        
        Public Function CreateOrder(ByVal publicKey As String, ByVal amount As Decimal) As Node.Order Implements Node.IAtm.CreateOrder
            Return MyBase.Channel.CreateOrder(publicKey, amount)
        End Function
        
        Public Function CreateOrderAsync(ByVal publicKey As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of Node.Order) Implements Node.IAtm.CreateOrderAsync
            Return MyBase.Channel.CreateOrderAsync(publicKey, amount)
        End Function
        
        Public Function TransferCoinsToBuyer(ByVal cardId As String, ByVal amount As Decimal) As String Implements Node.IAtm.TransferCoinsToBuyer
            Return MyBase.Channel.TransferCoinsToBuyer(cardId, amount)
        End Function
        
        Public Function TransferCoinsToBuyerAsync(ByVal cardId As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of String) Implements Node.IAtm.TransferCoinsToBuyerAsync
            Return MyBase.Channel.TransferCoinsToBuyerAsync(cardId, amount)
        End Function
        
        Public Function ReceiveCoins(ByVal encryptedPrivateKey As String, ByVal cardId As String, ByVal destinationAddress As String, ByVal amount As Decimal) As String Implements Node.IAtm.ReceiveCoins
            Return MyBase.Channel.ReceiveCoins(encryptedPrivateKey, cardId, destinationAddress, amount)
        End Function
        
        Public Function ReceiveCoinsAsync(ByVal encryptedPrivateKey As String, ByVal cardId As String, ByVal destinationAddress As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of String) Implements Node.IAtm.ReceiveCoinsAsync
            Return MyBase.Channel.ReceiveCoinsAsync(encryptedPrivateKey, cardId, destinationAddress, amount)
        End Function
        
        Public Function GetBalance(ByVal address As String, ByVal confirmations As Short) As Decimal Implements Node.IAtm.GetBalance
            Return MyBase.Channel.GetBalance(address, confirmations)
        End Function
        
        Public Function GetBalanceAsync(ByVal address As String, ByVal confirmations As Short) As System.Threading.Tasks.Task(Of Decimal) Implements Node.IAtm.GetBalanceAsync
            Return MyBase.Channel.GetBalanceAsync(address, confirmations)
        End Function
        
        Public Function SendBitcoins(ByVal encryptedPrivateKey As String, ByVal password As String, ByVal destinationAddress As String, ByVal amount As Decimal) As String Implements Node.IAtm.SendBitcoins
            Return MyBase.Channel.SendBitcoins(encryptedPrivateKey, password, destinationAddress, amount)
        End Function
        
        Public Function SendBitcoinsAsync(ByVal encryptedPrivateKey As String, ByVal password As String, ByVal destinationAddress As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of String) Implements Node.IAtm.SendBitcoinsAsync
            Return MyBase.Channel.SendBitcoinsAsync(encryptedPrivateKey, password, destinationAddress, amount)
        End Function
        
        Public Sub SendEmail(ByVal toAddress As String, ByVal subject As String, ByVal body As String) Implements Node.IAtm.SendEmail
            MyBase.Channel.SendEmail(toAddress, subject, body)
        End Sub
        
        Public Function SendEmailAsync(ByVal toAddress As String, ByVal subject As String, ByVal body As String) As System.Threading.Tasks.Task Implements Node.IAtm.SendEmailAsync
            Return MyBase.Channel.SendEmailAsync(toAddress, subject, body)
        End Function
    End Class
End Namespace
