//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public Nullable<decimal> CustomerID { get; set; }
        public System.DateTime DateIssued { get; set; }
        public string CardId { get; set; }
        public string Password { get; set; }
        public string PublicKey { get; set; }
        public string Pin { get; set; }
        public string Status { get; set; }
        public string PrivateKey { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
