//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Addresses = new HashSet<Address>();
            this.Cards = new HashSet<Card>();
            this.CustomerBanks = new HashSet<CustomerBank>();
            this.sends = new HashSet<send>();
        }
    
        public decimal CustomerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Identified { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<CustomerBank> CustomerBanks { get; set; }
        public virtual ICollection<send> sends { get; set; }
    }
}
