//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public decimal Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string CardId { get; set; }
        public string TransType { get; set; }
        public string TerminalId { get; set; }
        public string NumuratorCurrency { get; set; }
        public string DeominatorCurrency { get; set; }
        public decimal Amount { get; set; }
        public decimal Price { get; set; }
        public string Reference { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
