#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Payment
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DiamondCircle_db")]
	public partial class DCPaymentServiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DCPaymentServiceDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DiamondCircle_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCPaymentServiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCPaymentServiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCPaymentServiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCPaymentServiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addTransaction")]
		public ISingleResult<addTransactionResult> addTransaction([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateTime", DbType="DateTime")] System.Nullable<System.DateTime> dateTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardID", DbType="NChar(8)")] string cardID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransType", DbType="NChar(3)")] string transType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TerminalID", DbType="NChar(10)")] string terminalID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumuratorCurrency", DbType="NChar(3)")] string numuratorCurrency, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DeominatorCurrency", DbType="NChar(3)")] string deominatorCurrency, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Money")] System.Nullable<decimal> price, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reference", DbType="NVarChar(100)")] string reference)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateTime, cardID, transType, terminalID, numuratorCurrency, deominatorCurrency, amount, price, reference);
			return ((ISingleResult<addTransactionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCard")]
		public ISingleResult<getCardResult> getCard([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardID", DbType="NChar(8)")] string cardID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cardID);
			return ((ISingleResult<getCardResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.addCard")]
		public int addCard([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CardID", DbType="NChar(16)")] string cardID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublicKey", DbType="NChar(34)")] string publicKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pin", DbType="NChar(6)")] string pin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NChar(256)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateIssued", DbType="DateTime")] System.Nullable<System.DateTime> dateIssued)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cardID, publicKey, pin, password, dateIssued);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class addTransactionResult
	{
		
		private int _TransactionID;
		
		private int _InsertRowCount;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		public addTransactionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="Int NOT NULL")]
		public int TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this._TransactionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertRowCount", DbType="Int NOT NULL")]
		public int InsertRowCount
		{
			get
			{
				return this._InsertRowCount;
			}
			set
			{
				if ((this._InsertRowCount != value))
				{
					this._InsertRowCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
	}
	
	public partial class getCardResult
	{
		
		private string _CardId;
		
		private System.Nullable<decimal> _CustomerID;
		
		private System.DateTime _DateIssued;
		
		private string _Password;
		
		private string _PublicKey;
		
		private string _Pin;
		
		public getCardResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardId", DbType="NChar(8) NOT NULL", CanBeNull=false)]
		public string CardId
		{
			get
			{
				return this._CardId;
			}
			set
			{
				if ((this._CardId != value))
				{
					this._CardId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime NOT NULL")]
		public System.DateTime DateIssued
		{
			get
			{
				return this._DateIssued;
			}
			set
			{
				if ((this._DateIssued != value))
				{
					this._DateIssued = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(256)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicKey", DbType="NChar(34)")]
		public string PublicKey
		{
			get
			{
				return this._PublicKey;
			}
			set
			{
				if ((this._PublicKey != value))
				{
					this._PublicKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="NChar(6)")]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this._Pin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
