//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public decimal CustomerId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string LandLine { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public int ID { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public string State { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual AddressType AddressType1 { get; set; }
        public virtual country country { get; set; }
    }
}
