//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardCurrencyHistory
    {
        public int FiatHistoryId { get; set; }
        public int CardCurrencyId { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public string Reference { get; set; }
        public string TransactionDetails { get; set; }
        public string CreateUser { get; set; }
    
        public virtual CardCurrency CardCurrency { get; set; }
    }
}
