//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.Addresses = new HashSet<Address>();
            this.Currencies = new HashSet<Currency>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Currency> Currencies { get; set; }
    }
}
