//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardChargeType
    {
        public CreditCardChargeType()
        {
            this.CreditCardCharges = new HashSet<CreditCardCharge>();
        }
    
        public int CreditCardChargeTypeId { get; set; }
        public int CreditCardTypeId { get; set; }
        public decimal Percentage { get; set; }
        public int FinancialRegionId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<CreditCardCharge> CreditCardCharges { get; set; }
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual FinancialRegion FinancialRegion { get; set; }
    }
}
