//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public CreditCard()
        {
            this.Cards = new HashSet<Card>();
        }
    
        public System.Guid CreditCardId { get; set; }
        public string CardHolderName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CVC2 { get; set; }
        public bool Active { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public string AddressLine1 { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string ExpiryMonth { get; set; }
        public string ExpiryYear { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<Card> Cards { get; set; }
    }
}
