//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Addresses = new HashSet<Address>();
            this.CustomerBanks = new HashSet<CustomerBank>();
            this.TradingHistories = new HashSet<TradingHistory>();
            this.Cards = new HashSet<Card>();
            this.C_send = new HashSet<C_send>();
            this.OpenOrders = new HashSet<OpenOrder>();
        }
    
        public decimal CustomerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Identified { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailAddress { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Telephone { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<CustomerBank> CustomerBanks { get; set; }
        public virtual ICollection<TradingHistory> TradingHistories { get; set; }
        public virtual ICollection<Card> Cards { get; set; }
        public virtual ICollection<C_send> C_send { get; set; }
        public virtual ICollection<OpenOrder> OpenOrders { get; set; }
        public virtual Setting Setting { get; set; }
    }
}
