//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Margin
    {
        public int Id { get; set; }
        public string TerminalId { get; set; }
        public string FiatCurrency { get; set; }
        public decimal FiatAmount { get; set; }
        public Nullable<decimal> FiatFee { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
