//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.CommissionCharges = new HashSet<CommissionCharge>();
            this.CreditCardCharges = new HashSet<CreditCardCharge>();
        }
    
        public decimal Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string CardId { get; set; }
        public string TransType { get; set; }
        public string TerminalId { get; set; }
        public string NumuratorCurrency { get; set; }
        public string DeominatorCurrency { get; set; }
        public decimal Amount { get; set; }
        public decimal Price { get; set; }
        public string Reference { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual ICollection<CommissionCharge> CommissionCharges { get; set; }
        public virtual ICollection<CreditCardCharge> CreditCardCharges { get; set; }
    }
}
