// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace DC.Common.Models
{
    [DataContract]
    public class SingleAddressTransactionInputs
    {

        [DataMember(Name = "prev_out")]
        public List<TransactionOut> PreviousOut { get; set; }

        [DataMember(Name = "script")]
        public string Script { get; set; }


    }
}
