// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace DC.Common.Models
{
    [DataContract]
    public class SingleAddressTransaction
    {

        [DataMember(Name = "result")]
        public Int64 Result { get; set; }

        [DataMember(Name = "block_height")]
        public Int64 BlockHeight { get; set; }

        [DataMember(Name = "time")]
        public Int64 Time { get; set; }

        [DataMember(Name = "inputs")]
        public List<SingleAddressTransactionInputs> Inputs { get; set; }

        [DataMember(Name = "vout_sz")]
        public Int64 VOutSize { get; set; }

        [DataMember(Name = "relayed_by")]
        public string RelayedBy { get; set; }

        [DataMember(Name = "hash")]
        public string Hash { get; set; }

        [DataMember(Name = "vin_sz")]
        public Int64 VInSize { get; set; }

        [DataMember(Name = "tx_index")]
        public Int64 TransactionIndex { get; set; }

        [DataMember(Name = "ver")]
        public Int64 Version { get; set; }

        [DataMember(Name = "out")]
        public List<TransactionOut> Out { get; set; }

        [DataMember(Name = "size")]
        public Int64 size { get; set; }
    }
}
