// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace DC.Common.Models
{
    [DataContract]
    public class TransactionOut
    {

        [DataMember(Name = "n")]
        public Int64 Number { get; set; }

        [DataMember(Name = "value")]
        public Int64 Value { get; set; }

        [DataMember(Name = "addr")]
        public string Address { get; set; }

        [DataMember(Name = "tx_index")]
        public Int64 TransactionIndex { get; set; }

        [DataMember(Name = "spent")]
        public bool Spent { get; set; }

        [DataMember(Name = "type")]
        public Int64 Type { get; set; }

        [DataMember(Name = "script")]
        public string Script { get; set; }

    }
}
