// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace DC.Common.Models
{
    [DataContract]
    public class UnspentOutput
    {
        [DataMember(Name = "tx_hash")]
        public string TxHash { get; set; }

        [DataMember(Name = "tx_index")]
        public Int64 TxIndex { get; set; }

        [DataMember(Name = "tx_output_n")]
        public int TxOutputN { get; set; }

        [DataMember(Name = "script")]
        public string Script { get; set; }

        [DataMember(Name = "value")]
        public Int64 Value { get; set; }

        [DataMember(Name = "value_hex")]
        public string ValueHex { get; set; }

        [DataMember(Name = "confirmations")]
        public int Confirmations { get; set; }

        public Byte[] OutputIndexAsBytes
        {
            get
            {
                Byte[] previousOutputIndex = new Byte[4];
                previousOutputIndex = BitConverter.GetBytes(TxOutputN);
                return previousOutputIndex;
            }
        }

        public Byte[] ScryptAsBytes
        {
            get
            {
                if (!String.IsNullOrEmpty(this.Script))
                {
                    return DC.Common.StringHelper.HexStringToByte(this.Script);
                }
                else
                {
                    return null;
                }
            }
        }
    }
}
