//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public decimal CustomerId { get; set; }
        public string Currency { get; set; }
        public decimal Balance { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
