//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionType
    {
        public CommissionType()
        {
            this.CommissionCharges = new HashSet<CommissionCharge>();
        }
    
        public int CommissionTypeId { get; set; }
        public int RoleId { get; set; }
        public int SituationId { get; set; }
        public decimal Percentage { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModfiedDate { get; set; }
    
        public virtual ICollection<CommissionCharge> CommissionCharges { get; set; }
        public virtual Situation Situation { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
    }
}
