//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionCharge
    {
        public int CommissionChargeId { get; set; }
        public int CustomerRoleId { get; set; }
        public int CommissionTypeId { get; set; }
        public decimal TransactionId { get; set; }
        public decimal TransationPercent { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
    
        public virtual CommissionType CommissionType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
