//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardCharge
    {
        public int CreditCardChargeId { get; set; }
        public decimal PercentageCharged { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public decimal TransactionId { get; set; }
        public int CreditCardChargeTypeId { get; set; }
    
        public virtual CreditCardChargeType CreditCardChargeType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
