//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendBitcoin
    {
        public int SendBitcoinId { get; set; }
        public string CardId { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public decimal BTCAmount { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
