//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBank
    {
        public int Id { get; set; }
        public decimal CustomerId { get; set; }
        public string BSB { get; set; }
        public string AccountNumber { get; set; }
        public string PayPal { get; set; }
        public string SWIFT { get; set; }
        public string IBAN { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
