//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class send
    {
        public int Id { get; set; }
        public decimal CustomerId { get; set; }
        public string sender { get; set; }
        public string reciver { get; set; }
        public string status { get; set; }
        public System.DateTime date { get; set; }
        public decimal BitAmount { get; set; }
        public decimal AUDAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
