'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace DCCard
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CCInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/DC.Common.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CCInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CVC2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CardHolderNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CardNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DOBField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExpiryDateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExpiryMonthField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExpiryYearField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelephoneField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZipField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CVC2() As String
            Get
                Return Me.CVC2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.CVC2Field, value) <> true) Then
                    Me.CVC2Field = value
                    Me.RaisePropertyChanged("CVC2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CardHolderName() As String
            Get
                Return Me.CardHolderNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CardHolderNameField, value) <> true) Then
                    Me.CardHolderNameField = value
                    Me.RaisePropertyChanged("CardHolderName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CardNumber() As String
            Get
                Return Me.CardNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CardNumberField, value) <> true) Then
                    Me.CardNumberField = value
                    Me.RaisePropertyChanged("CardNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property City() As String
            Get
                Return Me.CityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CityField, value) <> true) Then
                    Me.CityField = value
                    Me.RaisePropertyChanged("City")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Country() As String
            Get
                Return Me.CountryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryField, value) <> true) Then
                    Me.CountryField = value
                    Me.RaisePropertyChanged("Country")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DOB() As String
            Get
                Return Me.DOBField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DOBField, value) <> true) Then
                    Me.DOBField = value
                    Me.RaisePropertyChanged("DOB")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailAddress() As String
            Get
                Return Me.EmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailAddressField, value) <> true) Then
                    Me.EmailAddressField = value
                    Me.RaisePropertyChanged("EmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExpiryDate() As String
            Get
                Return Me.ExpiryDateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExpiryDateField, value) <> true) Then
                    Me.ExpiryDateField = value
                    Me.RaisePropertyChanged("ExpiryDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExpiryMonth() As String
            Get
                Return Me.ExpiryMonthField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExpiryMonthField, value) <> true) Then
                    Me.ExpiryMonthField = value
                    Me.RaisePropertyChanged("ExpiryMonth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExpiryYear() As String
            Get
                Return Me.ExpiryYearField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExpiryYearField, value) <> true) Then
                    Me.ExpiryYearField = value
                    Me.RaisePropertyChanged("ExpiryYear")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property State() As String
            Get
                Return Me.StateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StateField, value) <> true) Then
                    Me.StateField = value
                    Me.RaisePropertyChanged("State")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Telephone() As String
            Get
                Return Me.TelephoneField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelephoneField, value) <> true) Then
                    Me.TelephoneField = value
                    Me.RaisePropertyChanged("Telephone")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Zip() As String
            Get
                Return Me.ZipField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZipField, value) <> true) Then
                    Me.ZipField = value
                    Me.RaisePropertyChanged("Zip")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OnlineAccount", [Namespace]:="http://schemas.datacontract.org/2004/07/DC.Common.Models"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OnlineAccount
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfirmTokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuccessField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ConfirmToken() As String
            Get
                Return Me.ConfirmTokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConfirmTokenField, value) <> true) Then
                    Me.ConfirmTokenField = value
                    Me.RaisePropertyChanged("ConfirmToken")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Success() As Boolean
            Get
                Return Me.SuccessField
            End Get
            Set
                If (Me.SuccessField.Equals(value) <> true) Then
                    Me.SuccessField = value
                    Me.RaisePropertyChanged("Success")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://payment.diamondcircle.net/v1", ConfigurationName:="DCCard.ICard")>  _
    Public Interface ICard
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/AddCardWithPIN", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/AddCardWithPINResponse")>  _
        Sub AddCardWithPIN(ByVal CardId As String, ByVal PublicKey As String, ByVal Password As String, ByVal PIN As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/AddCardWithPIN", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/AddCardWithPINResponse")>  _
        Function AddCardWithPINAsync(ByVal CardId As String, ByVal PublicKey As String, ByVal Password As String, ByVal PIN As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/AddCard", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/AddCardResponse")>  _
        Sub AddCard( _
                    ByVal CardId As String,  _
                    ByVal PublicKey As String,  _
                    ByVal Password As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal Address As String,  _
                    ByVal City As String,  _
                    ByVal Zip As String,  _
                    ByVal State As String,  _
                    ByVal Country As String,  _
                    ByVal Telephone As String,  _
                    ByVal DOB As String,  _
                    ByVal EmailAddress As String,  _
                    ByVal CardHolderName As String,  _
                    ByVal CardNumber As String,  _
                    ByVal ExpiryMonth As String,  _
                    ByVal ExpiryYear As String,  _
                    ByVal CVC2 As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/AddCard", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/AddCardResponse")>  _
        Function AddCardAsync( _
                    ByVal CardId As String,  _
                    ByVal PublicKey As String,  _
                    ByVal Password As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal Address As String,  _
                    ByVal City As String,  _
                    ByVal Zip As String,  _
                    ByVal State As String,  _
                    ByVal Country As String,  _
                    ByVal Telephone As String,  _
                    ByVal DOB As String,  _
                    ByVal EmailAddress As String,  _
                    ByVal CardHolderName As String,  _
                    ByVal CardNumber As String,  _
                    ByVal ExpiryMonth As String,  _
                    ByVal ExpiryYear As String,  _
                    ByVal CVC2 As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/GetCustomerCC", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/GetCustomerCCResponse")>  _
        Function GetCustomerCC(ByVal CardId As String) As DCCard.CCInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/GetCustomerCC", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/GetCustomerCCResponse")>  _
        Function GetCustomerCCAsync(ByVal CardId As String) As System.Threading.Tasks.Task(Of DCCard.CCInfo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/IsCardOnFile", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/IsCardOnFileResponse")>  _
        Function IsCardOnFile(ByVal CardId As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/IsCardOnFile", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/IsCardOnFileResponse")>  _
        Function IsCardOnFileAsync(ByVal CardId As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/GetHotWalletAddress", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/GetHotWalletAddressResponse")>  _
        Function GetHotWalletAddress() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/GetHotWalletAddress", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/GetHotWalletAddressResponse")>  _
        Function GetHotWalletAddressAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/AddOnlineAccount", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/AddOnlineAccountResponse")>  _
        Function AddOnlineAccount() As DCCard.OnlineAccount
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/AddOnlineAccount", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/AddOnlineAccountResponse")>  _
        Function AddOnlineAccountAsync() As System.Threading.Tasks.Task(Of DCCard.OnlineAccount)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/WriteTransaction", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/WriteTransactionResponse")>  _
        Function WriteTransaction(ByVal CardId As String, ByVal TransType As String, ByVal TerminalId As Integer, ByVal NumuratorCurrency As String, ByVal DenominatorCurrency As String, ByVal Amount As Decimal, ByVal Price As Decimal, ByVal Reference As String, ByVal TransactionID As Integer) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/WriteTransaction", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/WriteTransactionResponse")>  _
        Function WriteTransactionAsync(ByVal CardId As String, ByVal TransType As String, ByVal TerminalId As Integer, ByVal NumuratorCurrency As String, ByVal DenominatorCurrency As String, ByVal Amount As Decimal, ByVal Price As Decimal, ByVal Reference As String, ByVal TransactionID As Integer) As System.Threading.Tasks.Task(Of Decimal)
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/CreateaPayment", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/CreateaPaymentResponse")>  _
        Function CreateaPayment(ByVal PaymentProvider As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://payment.diamondcircle.net/v1/ICard/CreateaPayment", ReplyAction:="https://payment.diamondcircle.net/v1/ICard/CreateaPaymentResponse")>  _
        Function CreateaPaymentAsync(ByVal PaymentProvider As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICardChannel
        Inherits DCCard.ICard, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CardClient
        Inherits System.ServiceModel.ClientBase(Of DCCard.ICard)
        Implements DCCard.ICard
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub AddCardWithPIN(ByVal CardId As String, ByVal PublicKey As String, ByVal Password As String, ByVal PIN As String) Implements DCCard.ICard.AddCardWithPIN
            MyBase.Channel.AddCardWithPIN(CardId, PublicKey, Password, PIN)
        End Sub
        
        Public Function AddCardWithPINAsync(ByVal CardId As String, ByVal PublicKey As String, ByVal Password As String, ByVal PIN As String) As System.Threading.Tasks.Task Implements DCCard.ICard.AddCardWithPINAsync
            Return MyBase.Channel.AddCardWithPINAsync(CardId, PublicKey, Password, PIN)
        End Function
        
        Public Sub AddCard( _
                    ByVal CardId As String,  _
                    ByVal PublicKey As String,  _
                    ByVal Password As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal Address As String,  _
                    ByVal City As String,  _
                    ByVal Zip As String,  _
                    ByVal State As String,  _
                    ByVal Country As String,  _
                    ByVal Telephone As String,  _
                    ByVal DOB As String,  _
                    ByVal EmailAddress As String,  _
                    ByVal CardHolderName As String,  _
                    ByVal CardNumber As String,  _
                    ByVal ExpiryMonth As String,  _
                    ByVal ExpiryYear As String,  _
                    ByVal CVC2 As String) Implements DCCard.ICard.AddCard
            MyBase.Channel.AddCard(CardId, PublicKey, Password, FirstName, LastName, Address, City, Zip, State, Country, Telephone, DOB, EmailAddress, CardHolderName, CardNumber, ExpiryMonth, ExpiryYear, CVC2)
        End Sub
        
        Public Function AddCardAsync( _
                    ByVal CardId As String,  _
                    ByVal PublicKey As String,  _
                    ByVal Password As String,  _
                    ByVal FirstName As String,  _
                    ByVal LastName As String,  _
                    ByVal Address As String,  _
                    ByVal City As String,  _
                    ByVal Zip As String,  _
                    ByVal State As String,  _
                    ByVal Country As String,  _
                    ByVal Telephone As String,  _
                    ByVal DOB As String,  _
                    ByVal EmailAddress As String,  _
                    ByVal CardHolderName As String,  _
                    ByVal CardNumber As String,  _
                    ByVal ExpiryMonth As String,  _
                    ByVal ExpiryYear As String,  _
                    ByVal CVC2 As String) As System.Threading.Tasks.Task Implements DCCard.ICard.AddCardAsync
            Return MyBase.Channel.AddCardAsync(CardId, PublicKey, Password, FirstName, LastName, Address, City, Zip, State, Country, Telephone, DOB, EmailAddress, CardHolderName, CardNumber, ExpiryMonth, ExpiryYear, CVC2)
        End Function
        
        Public Function GetCustomerCC(ByVal CardId As String) As DCCard.CCInfo Implements DCCard.ICard.GetCustomerCC
            Return MyBase.Channel.GetCustomerCC(CardId)
        End Function
        
        Public Function GetCustomerCCAsync(ByVal CardId As String) As System.Threading.Tasks.Task(Of DCCard.CCInfo) Implements DCCard.ICard.GetCustomerCCAsync
            Return MyBase.Channel.GetCustomerCCAsync(CardId)
        End Function
        
        Public Function IsCardOnFile(ByVal CardId As String) As Boolean Implements DCCard.ICard.IsCardOnFile
            Return MyBase.Channel.IsCardOnFile(CardId)
        End Function
        
        Public Function IsCardOnFileAsync(ByVal CardId As String) As System.Threading.Tasks.Task(Of Boolean) Implements DCCard.ICard.IsCardOnFileAsync
            Return MyBase.Channel.IsCardOnFileAsync(CardId)
        End Function
        
        Public Function GetHotWalletAddress() As String Implements DCCard.ICard.GetHotWalletAddress
            Return MyBase.Channel.GetHotWalletAddress
        End Function
        
        Public Function GetHotWalletAddressAsync() As System.Threading.Tasks.Task(Of String) Implements DCCard.ICard.GetHotWalletAddressAsync
            Return MyBase.Channel.GetHotWalletAddressAsync
        End Function
        
        Public Function AddOnlineAccount() As DCCard.OnlineAccount Implements DCCard.ICard.AddOnlineAccount
            Return MyBase.Channel.AddOnlineAccount
        End Function
        
        Public Function AddOnlineAccountAsync() As System.Threading.Tasks.Task(Of DCCard.OnlineAccount) Implements DCCard.ICard.AddOnlineAccountAsync
            Return MyBase.Channel.AddOnlineAccountAsync
        End Function
        
        Public Function WriteTransaction(ByVal CardId As String, ByVal TransType As String, ByVal TerminalId As Integer, ByVal NumuratorCurrency As String, ByVal DenominatorCurrency As String, ByVal Amount As Decimal, ByVal Price As Decimal, ByVal Reference As String, ByVal TransactionID As Integer) As Decimal Implements DCCard.ICard.WriteTransaction
            Return MyBase.Channel.WriteTransaction(CardId, TransType, TerminalId, NumuratorCurrency, DenominatorCurrency, Amount, Price, Reference, TransactionID)
        End Function
        
        Public Function WriteTransactionAsync(ByVal CardId As String, ByVal TransType As String, ByVal TerminalId As Integer, ByVal NumuratorCurrency As String, ByVal DenominatorCurrency As String, ByVal Amount As Decimal, ByVal Price As Decimal, ByVal Reference As String, ByVal TransactionID As Integer) As System.Threading.Tasks.Task(Of Decimal) Implements DCCard.ICard.WriteTransactionAsync
            Return MyBase.Channel.WriteTransactionAsync(CardId, TransType, TerminalId, NumuratorCurrency, DenominatorCurrency, Amount, Price, Reference, TransactionID)
        End Function
        
        Public Function CreateaPayment(ByVal PaymentProvider As String) As Boolean Implements DCCard.ICard.CreateaPayment
            Return MyBase.Channel.CreateaPayment(PaymentProvider)
        End Function
        
        Public Function CreateaPaymentAsync(ByVal PaymentProvider As String) As System.Threading.Tasks.Task(Of Boolean) Implements DCCard.ICard.CreateaPaymentAsync
            Return MyBase.Channel.CreateaPaymentAsync(PaymentProvider)
        End Function
    End Class
End Namespace
