// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace DC.Common.Models
{
    [DataContract]
    public class SingleAddressResponse
    {

        [DataMember(Name = "hash160")]
        public string Hash160 { get; set; }

        [DataMember(Name = "address")]
        public string Address { get; set; }

        [DataMember(Name = "n_tx")]
        public int NumberOfTransactions { get; set; }

        [DataMember(Name = "n_unredeemed")]
        public string NumberUnredeemed { get; set; }

        [DataMember(Name = "total_received")]
        public Int64 TotalReceived { get; set; }

        [DataMember(Name = "total_sent")]
        public string TotalSent { get; set; }

        [DataMember(Name = "final_balance")]
        public int FinalBalance { get; set; }

        [DataMember(Name = "txs")]
        public List<SingleAddressTransaction> Transactions { get; set; }
    }
}
